name: Java CI with Gradle

on:
  workflow_run:
    workflows: [ "Super-Linter" ]
    types:
      - completed
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clean Gradle cache
        run: ./gradlew clean

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: ./gradlew sonarqube -Dsonar.projectKey=hinmiro_PlannerServer -Dsonar.organization=Miro Hintikka -Dsonar.host.url=https://sonarcloud.io

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v3
        with:
          script: |
            const { context } = require('@actions/github');
            const issueTitle = `Test failed on push to ${context.ref}`;
            const issueBody = `A test failed on push to ${context.ref}. Please check the workflow logs for details.`;
            await github.issues.create({
              ...context.repo,
              title: issueTitle,
              body: issueBody,
            });


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
